# Generated by Django 2.1.7 on 2019-07-14 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploytodotaskerapp', '0002_auto_20190713_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deploytodotaskerapp.Meal'),
        ),
    ]
